### ISSUE TITLE
"evictionidle()" and "evictionPredicate()" on PoolBuilder cannot be used together

### ISSUE THREAD

**Issue by ttddyy** [reactor/reactor-pool#33]
This is because `evictionidle()` internally set `evictionPredicate()` with `idlePredicate`; thus, previously set or setting another predicate to `evictionPredicate()` will override the existing one.

This can be worked around in caller side to create a composite predicate for doing idle time check and another whatever predicate logic.

I am wondering is it better to have such composite predicate in pool builder side, and instead of overriding predicate by `evictionidle()` and `evictionPredicate()`, simply adding them to the composite predicate and chain them as "**OR**" semantics?

**Comment by simonbasle** [comment]
Eviction predicates were initially offered as composable pre-built `Functions` via `EvictionPredicates`, but @nebhale and @smaldini argued against it because only the idle one was deemed useful, so it was removed in #10.

Coming up with a `Predicate` that directly checks both idle and custom logic should be easy enough, though. Plus `Predicate` composition is also always possible.

The idea of the two methods on the builder was that most of the time a simple `idlePredicate` would be enough, but `evictionPredicate(Predicate)` offers an escape hatch for more complex cases.

**Comment by smaldini** [comment]
I wonder if we need to keep the idle alias in fact as it might be more clear to just leave the user implement it (slightly more verbose ?)

**Comment by simonbasle** [comment]
I'll clarify this behavior in the documentation, including the piece of code users can use to reproduce the `evictionIdle` when combining this logic with some custom logic is needed.
